import type { DecideContext } from "./types";

export const contexts: Record<string, DecideContext> = {
  home: {
    id: "home",
    label: "Home · Fairfax · Sun PM",
    loc: "Fairfax, VA",
    city: "dc",
    time: "Sun · 5:32 PM",
    tod: "evening",
    dow: "weekend",
    weather: "72°, clear",
    weatherIcon: "sun",
    season: "Late spring",
    seasonTag: "spring",
    weatherTag: "warm",
    vibe: "cozy",
    greetT: "Sunday wind-down mode",
    greetS: "Lower-effort, comforting picks. Tune as you go.",
  },
  la: {
    id: "la",
    label: "7pm in LA, October",
    loc: "Los Angeles",
    city: "la",
    time: "Thu · 7:04 PM",
    tod: "evening",
    dow: "weekday",
    weather: "68°, dry",
    weatherIcon: "sun",
    season: "October",
    seasonTag: "fall",
    weatherTag: "mild",
    vibe: "energetic",
    greetT: "You just landed in LA",
    greetS: "Late but the city is awake. Here's a clean evening.",
  },
  tokyo: {
    id: "tokyo",
    label: "Tokyo morning, winter",
    loc: "Shibuya, Tokyo",
    city: "tokyo",
    time: "Sat · 8:12 AM",
    tod: "morning",
    dow: "weekend",
    weather: "46°, crisp",
    weatherIcon: "cloud",
    season: "February",
    seasonTag: "winter",
    weatherTag: "cold",
    vibe: "fresh",
    greetT: "Crisp Tokyo morning",
    greetS: "Light, warming, walkable picks for a slow Saturday start.",
  },
  rainy: {
    id: "rainy",
    label: "Rainy Tuesday night home",
    loc: "Fairfax, VA",
    city: "dc",
    time: "Tue · 9:18 PM",
    tod: "late-night",
    dow: "weekday",
    weather: "58°, rain",
    weatherIcon: "rain",
    season: "November",
    seasonTag: "fall",
    weatherTag: "rainy",
    vibe: "cocoon",
    greetT: "Cocoon mode",
    greetS: "Stay in. Eat well. Watch something good. Sleep early.",
  },
  saturday: {
    id: "saturday",
    label: "Saturday morning, sunny",
    loc: "Fairfax, VA",
    city: "dc",
    time: "Sat · 9:21 AM",
    tod: "morning",
    dow: "weekend",
    weather: "74°, sunny",
    weatherIcon: "sun",
    season: "June",
    seasonTag: "summer",
    weatherTag: "sunny",
    vibe: "energetic",
    greetT: "Big Saturday energy",
    greetS: "Movement first, then a proper breakfast and a long read.",
  },
};

export const DEFAULT_CONTEXT_ID = "home";
